name: Build APK with Docker
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest # Buildozer නිල Docker image එක

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
            # Docker එක ඇතුළේ දැනටමත් හැමදේම ලෑස්තියි
            buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ravana-apk
          path: bin/*.apk
